### PR TITLE
more delimiters

### PR DESCRIPTION
**Pull request by metasyn**

### CODE REVIEW

**Comment by dwhieb** [comment]
Looks like we've got a merge conflict. I won't be able to resolve it until tomorrow probably - do you want to discard your branch (but keep the files), start a new one, and copy in your changes then push again? If not I'll compare the files and incorporate your changes tomorrow.

**Comment by dwhieb** [comment]
Whoa, now them's some delimiters

**Comment by amundo** [comment]
neat. @metasyn did this list of delimiters come from somewhere else? 

seems like it woudl make sense down the road to refactor this into a punctuation module or something, or perhaps into the default set of punctuation delimiters for a `Language` or `Orthography` object.

**Comment by dwhieb** [comment]
I second that idea

**Comment by metasyn** [comment]
Third this idea !

No; its not an official list. The long list of unicode's are related to different types of quote markers, that I scraped from here: http://en.wikipedia.org/wiki/Quotation_mark#Unicode_code_point_table

**Comment by amundo** [comment]
Here's a scenario that keeps popping in my mind with this: punctuation needs to be orthography-specific. Forex, Hiligaynon uses a dash for a glottal stop. So tokenization  will either have to work by finding sequences of known-good (phonemic) characters, and everything else will be a delimiter, or we'll have to subtract the intersection of alphabetical and punctuation characters before splitting.

**Comment by metasyn** [comment]
so... JSON of valid characters for each orthography? Starting to sound like sbtrans.

**Comment by amundo** [comment]
It sure does. @dwhieb & I have been talking about what it would take to represent an orthography for a given language. If you start with a phonemic inventory consisting of all the phones in the language, then an orthographic inventory can be defined as a mapping onto the phonemic inventory. This is assuming that your phonemic orthography  is more or less phonemic itself. For a language like English with a crazy orthography, we'll  probably just have to store the spelling with the word in the lexicon. 

But yes, transliteration can be thought of as a side product of a well-defined orthographic representation.

**Pull request merged**
